eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-0.eureka.backend-wtdnow.svc.cluster.local:8761/eureka/
  instance:
    hostname: localhost
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true

#microservice:
#  payment-service:
#    endpoints:
#      endpoint:
#        uri: http://PAYMENT-SERVICE/payment-service
#  customer-service:
#    endpoints:
#      endpoint:
#        uri: http://CUSTOMER-SERVICE/customer-service
#  business-service:
#    endpoints:
#      endpoint:
#        uri: http://business-service-clusterip-service/business-service
#  security-service:
#    endpoints:
#      endpoint:
#        uri: http://security-service-clusterip-service/business-service
