
security:
  oauth2:
    client:
      registration:
        customer-service:
          client-id: customer-service-client
          client-secret: ioBejyAl6JeNnf1weHmIbAEt8FNoknHfYKA3SdhbJIk
        business-service:
          client-id: business-service-client
          client-secret: VVzF_aUubJzgtrhVE8SxEvUR-7AHym9TRFio5p1x4V4
        payment-service:
          client-id: payment-service-client
          client-secret: da94r1Gzh-yif2PmV3YTYePqUT5OeFr58rHE5Jb9zHk
spring:
  # Kafka Producer Configuration
  kafka:
    bootstrap-servers: ${KAFKA_SERVICE:kafka-service:9092}
    producer:
      bootstrap-servers: ${KAFKA_SERVICE:kafka-service:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.StringOrBytesSerializer

    # Kafka Consumer Configuration
    consumer:
      bootstrap-servers: ${KAFKA_SERVICE:kafka-service:9092}
      group-id: user-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer  
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true

# OAuth2 resource config
oauth2:
  google:
    api:
      verifier: ${GOOGLE_VERIFIER:https://www.googleapis.com/oauth2/v3/certs}
      issuer: ${GOOGLE_ISSUER:https://accounts.google.com}
  apple:
    api:
      verifier: ${APPLE_VERIFIER:https://appleid.apple.com/auth/keys}
      issuer: ${APPLE_ISSUER:https://appleid.apple.com}
  wtdnow:
    api:
      verifier: ${WTD_NOW_VERIFIER:http://security-server-svc/oauth2/jwks}
      issuer: ${WTD_NOW_ISSUER:https://uat.wtdnow.com}
logging:
  level:
    org:
      springframework:
        security: TRACE
CLOUD_GATEWAY_PORT: 8989
LOGO_PATH: /Users/eliasqayumi/what-to-do.png

